### ISSUE TITLE
호가창에 애니메이션 추가하기

### ISSUE THREAD

**Issue by mr-yoo** [sharebook-kr/arbitrage#2]
시각화 효과 추가합니다.

**Comment by mr-yoo** [comment]
다음과 같이 기능을 추가했습니다.
![image](https://user-images.githubusercontent.com/29349211/168441683-b4978d9b-68c6-4954-b6be-62719ec4f0bb.png)

**Comment by brayden-jo** [comment]
![arbo05](https://user-images.githubusercontent.com/23475470/168498046-cac64041-2a6f-4223-8cb5-33ac8cc4d1d2.gif)
